const shipments=[
{cte:'CTE-843921',cliente:'Atlas Home',origem:'Campinas, SP',destino:'Sao Paulo, SP',status:'Em rota',previsao:'Hoje 17:40',motorista:'Marcos Lima',volumes:18,peso:420,nf:'NF 223918'},
{cte:'CTE-843884',cliente:'Nova Farma',origem:'Jundiai, SP',destino:'Santos, SP',status:'Atrasado',previsao:'Hoje 15:10',motorista:'Bianca Prado',volumes:9,peso:120,nf:'NF 884192'},
{cte:'CTE-843777',cliente:'Mercado Sol',origem:'Campinas, SP',destino:'Osasco, SP',status:'Coleta',previsao:'Hoje 16:00',motorista:'Rafael Costa',volumes:31,peso:880,nf:'NF 109233'},
{cte:'CTE-843690',cliente:'EletroMax',origem:'Guarulhos, SP',destino:'Sao Bernardo, SP',status:'Em transferencia',previsao:'Amanha 09:20',motorista:'Patricia Nunes',volumes:44,peso:1360,nf:'NF 762140'},
{cte:'CTE-843615',cliente:'Petra Auto',origem:'Curitiba, PR',destino:'Campinas, SP',status:'Pendente',previsao:'Hoje 18:30',motorista:'Aguardando',volumes:11,peso:260,nf:'NF 441209'}];
let collections=[
{id:'COL-2091',cliente:'Atlas Home',remetente:'CD Campinas',destino:'Sao Paulo, SP',janela:'Hoje, 14:00-16:00',volumes:18,peso:420,status:'Agendada'},
{id:'COL-2088',cliente:'Mercado Sol',remetente:'Loja Anhanguera',destino:'Osasco, SP',janela:'Hoje, 16:00-18:00',volumes:31,peso:880,status:'Pendente'},
{id:'COL-2075',cliente:'Petra Auto',remetente:'Terminal Curitiba',destino:'Campinas, SP',janela:'Amanha, 08:00-10:00',volumes:11,peso:260,status:'Confirmada'}];
const trips=[
{id:'MAN-5527',rota:'SP Capital expressa',placa:'FRT-3A91',motorista:'Marcos Lima',status:'Em rota',progresso:64,volumes:126,peso:'3.8 t',docs:['CTE-843921','CTE-843884','CTE-843777'],paradas:['Jundiai','Osasco','Sao Paulo','Santos']},
{id:'MAN-5521',rota:'Interior consolidada',placa:'LOG-8C11',motorista:'Patricia Nunes',status:'Em transferencia',progresso:38,volumes:92,peso:'2.1 t',docs:['CTE-843690','CTE-843615'],paradas:['Limeira','Campinas','Jundiai']},
{id:'MAN-5514',rota:'Baixada agendada',placa:'BRZ-1D04',motorista:'Bianca Prado',status:'Atrasado',progresso:82,volumes:74,peso:'1.4 t',docs:['CTE-843884'],paradas:['Sao Paulo','Santos']}];
const events=['Coleta programada - Hoje 09:12','Carga coletada - Hoje 14:38','Em transferencia - Hoje 15:26','Saiu para entrega - Hoje 16:08','Previsao atualizada - Hoje 16:42'];
let selectedTrip=trips[0].id;
const $=id=>document.getElementById(id);
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2400)}
function cls(status){return status==='Atrasado'?'bad':status==='Pendente'?'warn':status==='Em rota'||status==='Confirmada'?'ok':'info'}
function pill(status){return `<span class="pill ${cls(status)}">${status}</span>`}
function view(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('show',v.id===id));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));document.querySelector('.sidebar').classList.remove('open')}
function renderKpis(){const data=[['Coletas pendentes',collections.filter(c=>c.status==='Pendente').length],['Entregas em rota',shipments.filter(s=>s.status==='Em rota').length],['Ocorrencias criticas',shipments.filter(s=>s.status==='Atrasado').length],['Volumes no dia',shipments.reduce((a,s)=>a+s.volumes,0)]];$('kpis').innerHTML=data.map(([a,b])=>`<article class="kpi"><span>${a}</span><strong>${b}</strong></article>`).join('')}
function renderBoard(filter=''){const columns=['Coleta','Em transferencia','Em rota','Atrasado'];filter=filter.toLowerCase();$('board').innerHTML=columns.map(col=>{const items=shipments.filter(s=>s.status===col&&`${s.cte} ${s.cliente} ${s.destino} ${s.status}`.toLowerCase().includes(filter));return `<article class="column"><header><span>${col}</span><span>${items.length}</span></header>${items.map(s=>`<button class="card" data-track="${s.cte}"><strong>${s.cte}</strong><div class="meta"><span>${s.cliente}</span><span>${s.destino}</span><span>${s.previsao}</span></div></button>`).join('')}</article>`}).join('')}
function renderRoutes(){$('routes').innerHTML=['Campinas -> Jundiai: 12 coletas consolidadas','Jundiai -> Sao Paulo: transito elevado','Sao Paulo -> Santos: 1 ocorrencia'].map(x=>`<p class="muted">${x}</p>`).join('')}
function renderPriority(){$('priority').innerHTML=shipments.map(s=>`<div class="row"><strong>${s.cte}</strong><span>${s.cliente}</span><span>${s.destino}</span>${pill(s.status)}</div>`).join('')}
function renderCollections(filter='Todas'){const list=collections.filter(c=>filter==='Todas'||c.status===filter);$('collections').innerHTML=list.map(c=>`<article class="card"><strong>${c.id} - ${c.cliente}</strong><div class="meta"><span>${c.remetente}</span><span>${c.destino}</span><span>${c.volumes} volumes</span><span>${c.peso} kg</span></div><p>${pill(c.status)}</p></article>`).join('')}
function renderTrips(){const list=trips.map(t=>`<button class="card" data-trip="${t.id}"><strong>${t.id}</strong><div class="meta"><span>${t.rota}</span><span>${t.placa}</span></div><div class="progress"><span style="width:${t.progresso}%"></span></div><p>${pill(t.status)}</p></button>`).join('');$('trips').innerHTML=`<h2>Manifestos ativos</h2>${list}`;const t=trips.find(x=>x.id===selectedTrip)||trips[0];$('tripDetail').innerHTML=`<h2>${t.rota}</h2><p class="muted">${t.motorista} - ${t.placa}</p><div class="kpis"><article class="kpi"><span>Volumes</span><strong>${t.volumes}</strong></article><article class="kpi"><span>Peso</span><strong>${t.peso}</strong></article><article class="kpi"><span>Paradas</span><strong>${t.paradas.length}</strong></article></div>${t.docs.map(d=>`<div class="row"><strong>${d}</strong><span>${shipments.find(s=>s.cte===d)?.cliente||''}</span><span>${shipments.find(s=>s.cte===d)?.destino||''}</span>${pill(shipments.find(s=>s.cte===d)?.status||'Pendente')}</div>`).join('')}`}
function renderTracking(code='CTE-843921'){const s=shipments.find(x=>x.cte.toLowerCase()===code.toLowerCase())||shipments[0];$('trackingCard').innerHTML=`<h2>${s.cte}</h2><p>${s.cliente} - ${s.nf}</p>${pill(s.status)}<div class="kpis"><article class="kpi"><span>Origem</span><strong>${s.origem}</strong></article><article class="kpi"><span>Destino</span><strong>${s.destino}</strong></article><article class="kpi"><span>Previsao</span><strong>${s.previsao}</strong></article><article class="kpi"><span>Motorista</span><strong>${s.motorista}</strong></article></div>`;$('timeline').innerHTML=events.map(e=>`<div class="timeline-item"><strong>${e.split(' - ')[0]}</strong><p class="muted">${e.split(' - ')[1]}</p></div>`).join('')}
function renderDriver(){$('driverStops').innerHTML=shipments.filter(s=>['Em rota','Atrasado','Coleta'].includes(s.status)).map(s=>`<button class="card" data-stop="${s.cte}"><strong>${s.destino}</strong><div class="meta"><span>${s.cte}</span><span>${s.cliente}</span></div></button>`).join('');$('deliverySummary').innerHTML=['CT-e: CTE-843921','Recebedor: pendente','Geolocalizacao: Sao Paulo, SP','Comprovantes: 0 de 2'].map(x=>`<p>${x}</p>`).join('')}
function saveCollection(){const f=$('collectionForm');if(!f.reportValidity())return;const d=new FormData(f);collections=[{id:`COL-${2100+collections.length}`,cliente:d.get('cliente'),remetente:d.get('remetente'),destino:d.get('destino'),janela:d.get('janela'),volumes:+d.get('volumes'),peso:+d.get('peso'),status:'Pendente'},...collections];renderCollections();renderKpis();toast('Coleta criada na fila')}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>view(b.dataset.open));$('menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');$('search').oninput=e=>renderBoard(e.target.value);$('saveCollection').onclick=saveCollection;$('runTracking').onclick=()=>{renderTracking($('trackingSearch').value);toast('Tracking atualizado')};$('copyTracking').onclick=()=>toast(`Link: https://tracking.nexatms.local/${$('trackingSearch').value}`);$('confirmDelivery').onclick=()=>toast('Entrega confirmada e comprovante enviado');document.addEventListener('click',e=>{const track=e.target.closest('[data-track]');if(track){$('trackingSearch').value=track.dataset.track;renderTracking(track.dataset.track);view('tracking')}const trip=e.target.closest('[data-trip]');if(trip){selectedTrip=trip.dataset.trip;renderTrips()}const stop=e.target.closest('[data-stop]');if(stop){$('scanCode').textContent=stop.dataset.stop;toast(`${stop.dataset.stop} selecionado`)}});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderCollections(b.dataset.filter)});document.querySelectorAll('.proof button').forEach(b=>b.onclick=()=>b.classList.toggle('done'));
renderKpis();renderBoard();renderRoutes();renderPriority();renderCollections();renderTrips();renderTracking();renderDriver();
